const express = require('express');
const controller = require('../../controllers/company_co/company_co');
const { verifyCompanyCoordinator } = require('../../modules/auth/auth.middleware');

const router = express.Router();

router.get('/home-stats', verifyCompanyCoordinator, controller.getHomeStats);
router.get('/dashboard/filters', verifyCompanyCoordinator, controller.getDashboardFilters);
router.get('/dashboard/summary', verifyCompanyCoordinator, controller.getDashboardSummary);
router.get('/dashboard/key-controls', verifyCompanyCoordinator, controller.getDashboardKeyControlStats);
router.get('/dashboard/nature-of-control', verifyCompanyCoordinator, controller.getDashboardNatureStats);
router.get('/dashboard/control-type', verifyCompanyCoordinator, controller.getDashboardControlTypeStats);
router.get('/dashboard/racms', verifyCompanyCoordinator, controller.getDashboardRacms);
router.get('/risk-analysis/availability', verifyCompanyCoordinator, controller.getRiskAnalysisAvailability);
router.get('/risk-analysis/control/:control_number', verifyCompanyCoordinator, controller.getRiskAnalysisByControl);
router.post('/risk-analysis/control/:control_number/generate', verifyCompanyCoordinator, controller.generateRiskAnalysisByControl);
router.get('/ai-insights/key-manual-summary/availability', verifyCompanyCoordinator, controller.getKeyManualAiInsightsAvailability);
router.get('/ai-insights/key-manual-summary', verifyCompanyCoordinator, controller.getKeyManualAiInsightsRun);
router.post('/ai-insights/key-manual-summary/generate', verifyCompanyCoordinator, controller.generateKeyManualAiInsightsRun);
router.delete('/ai-insights/key-manual-summary/:run_id', verifyCompanyCoordinator, controller.deleteKeyManualAiInsightsRun);
router.get('/racm-audit-logs/:form_id', verifyCompanyCoordinator, controller.getRacmAuditLogs);
router.get('/communication-matrix', verifyCompanyCoordinator, controller.getCommunicationMatrix);
router.post('/communication-matrix/common', verifyCompanyCoordinator, controller.addCommonCommunicationEmails);
router.post('/communication-matrix/specific', verifyCompanyCoordinator, controller.addBusinessProcessSpecificCommunicationEmails);
router.post('/communication-matrix/delete', verifyCompanyCoordinator, controller.deleteCommunicationMatrixEntries);
router.get('/users', verifyCompanyCoordinator, controller.getUsers);
router.get('/assigned-units', verifyCompanyCoordinator, controller.getAssignedUnits);
router.get('/approvers/:email_id/assignments', verifyCompanyCoordinator, controller.getApproverAssignments);
router.post('/racm-approver-assignments', verifyCompanyCoordinator, controller.assignRacmApprover);
router.get('/unit-management', verifyCompanyCoordinator, controller.getUnitManagement);
router.post('/unit-management/coordinators', verifyCompanyCoordinator, controller.createUnitCoordinator);
router.post('/unit-management/approvers', verifyCompanyCoordinator, controller.createUnitApprover);
router.post('/unit-management/units', verifyCompanyCoordinator, controller.createCompanyUnit);
router.patch('/unit-management/units/:unit_id/assignment', verifyCompanyCoordinator, controller.updateUnitAssignment);
router.post('/create-user', verifyCompanyCoordinator, controller.createUser);
router.post('/create-users-bulk', verifyCompanyCoordinator, controller.createUsersBulk);
router.post('/delete-users', verifyCompanyCoordinator, controller.deleteUsers);
router.get('/check-user', verifyCompanyCoordinator, controller.checkUser);
router.get('/check-user-role', verifyCompanyCoordinator, controller.checkUserRole);

module.exports = router;
