import React, { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import { useTheme } from '@mui/material/styles'
import { Link as RouterLink, useNavigate } from 'react-router-dom'
import Button from '@mui/material/Button'
import Box from '@mui/material/Box'
import Paper from '@mui/material/Paper'
import Typography from '@mui/material/Typography'
import TextField from '@mui/material/TextField'
import MenuItem from '@mui/material/MenuItem'
import FormControl from '@mui/material/FormControl'
import InputLabel from '@mui/material/InputLabel'
import Select from '@mui/material/Select'
import IconButton from '@mui/material/IconButton'
import InputAdornment from '@mui/material/InputAdornment'
import Link from '@mui/material/Link'
import Stack from '@mui/material/Stack'
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider'
import { DatePicker } from '@mui/x-date-pickers/DatePicker'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import ChecklistRoundedIcon from '@mui/icons-material/ChecklistRounded'
import LightbulbOutlinedIcon from '@mui/icons-material/LightbulbOutlined'
import { toast } from 'react-hot-toast'
import dayjs from 'dayjs'
import { FORM_DETAIL_MAX_WIDTH } from '../../uiConstants'
import { apiUrl, API_BASE_URL } from '../../config/api'
import { useBusinessProcesses } from '../../hooks/useBusinessProcesses'
import { useSyncGlobalLoading } from '../../contexts/GlobalLoadingContext'
import RacmUserAssignmentSection from '../../components/company_co/RacmUserAssignmentSection'
import ActiveRacmTemplateNotice from '../../components/company_co/ActiveRacmTemplateNotice'
import CustomColumnDot from '../../components/racm/CustomColumnDot'
import { RacmTemplateSectionFields } from '../../components/racm/RacmTemplateSectionFields'
import AppDialog, { APP_DIALOG_PRIMARY_BUTTON_SX } from '../../components/AppDialog'
import { getEffectiveSampleSizeForFrequency, validateSampleSizeForFrequency } from '../../utils/controlFrequencyValidation'

function createEmptyFormData(unitId = '') {
  return {
    business_process: '',
    financial_year: '',
    unit_id: unitId,
    control_number: '',
    area: '',
    risk_heat: '',
    standard_control_description: '',
    sub_process: '',
    risk_description: '',
    whether_fraud_risks_exist: '',
    control_objective: '',
    process_walkthrough: '',
    control_relies_on_ipe: '',
    audit_evidence_accuracy: '',
    ipe_reference: '',
    key_control: '',
    application_name: '',
    control_performer: '',
    control_owner: '',
    control_type_fo: '',
    control_type_ma: '',
    nature_of_control: '',
    control_frequency: '',
    sample_size: '',
    due_date: '',
    reminder_frequency: '',
  }
}

const DEFAULT_SECTION_LABELS = {
  process_and_risk: 'Process and Risk',
  assertions: 'Assertions',
  control_details: 'Control Details',
  others: 'Others',
}

const EMPTY_CONTROL_NUMBER_META = {
  autoGenerated: false,
  checkingDuplicate: false,
  duplicate: false,
  available: false,
}

function CreateControlForm() {
  const theme = useTheme()
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [companyIdentifier, setCompanyIdentifier] = useState('')
  const [unitOptions, setUnitOptions] = useState([])
  const controlNumberDebounceRef = useRef(null)
  const { businessProcessOptions, loading: businessProcessesLoading } = useBusinessProcesses()
  const [controlNumberMeta, setControlNumberMeta] = useState(EMPTY_CONTROL_NUMBER_META)
  const [assignmentSectionKey, setAssignmentSectionKey] = useState(0)
  const [racmTemplate, setRacmTemplate] = useState(null)
  const [extraTemplateFields, setExtraTemplateFields] = useState([])
  const [sectionLabels, setSectionLabels] = useState(DEFAULT_SECTION_LABELS)
  const [dynamicValues, setDynamicValues] = useState({})
  const [templateLoading, setTemplateLoading] = useState(false)
  const [templateHelpDialogOpen, setTemplateHelpDialogOpen] = useState(false)
  useSyncGlobalLoading(loading || templateLoading)

  // Financial year options - dynamically based on current year
  // Example: if current year is 2026 -> [ '2025-26', '2026-27' ]
  const currentYear = new Date().getFullYear()
  const baseFYStart = currentYear - 1
  const financialYearOptions = Array.from({ length: 2 }, (_, i) => {
    const startYear = baseFYStart + i
    const endYearShort = String((startYear + 1) % 100).padStart(2, '0')
    return `${startYear}-${endYearShort}`
  })

  // Form state - all fields that coordinators can create
  const [formData, setFormData] = useState(() => createEmptyFormData())

  const dropdownOptions = {
  risk_heat: ['High', 'Low', 'Medium'],
  control_type_fo: ['Financial', 'Operational'],
  control_type_ma: ['Manual', 'Automated'],
  nature_of_control: ['Preventive', 'Detective'],
  key_control: ['Yes', 'No'],
  control_relies_on_ipe: ['Yes', 'No'],
    control_frequency: [
      'Yearly',
      'Quarterly',
      'Half Yearly',
      'Monthly',
      'Weekly',
      'Fortnightly',
      'As and When Needed',
      'Recurring and Daily',
    ],
    whether_fraud_risks_exist: ['Yes', 'No']
  }

  const [dropdownSelections, setDropdownSelections] = useState({})
  const [otherValues, setOtherValues] = useState({})
  const [unitSampleSizeSettings, setUnitSampleSizeSettings] = useState([])
  const hasReminderValues =
    String(formData.due_date || '').trim() !== '' ||
    String(formData.reminder_frequency || '').trim() !== ''

  const getTomorrowDateString = () => {
    const d = new Date()
    d.setDate(d.getDate() + 1)
    return d.toISOString().split('T')[0]
  }

  const handleResetReminderSettings = () => {
    setFormData((prev) => ({
      ...prev,
      due_date: '',
      reminder_frequency: '',
    }))
  }

  useEffect(() => {
    // Fetch user's company_identifier
    const fetchUserInfo = async () => {
      try {
        const response = await fetch(apiUrl('/api/auth/verify'), {
          method: 'GET',
          credentials: 'include',
        })

        const data = await response.json()

        if (response.ok && data.success && data.user.company_identifier) {
          setCompanyIdentifier(data.user.company_identifier)
        }
      } catch (error) {
        console.error('Error fetching user info:', error)
      }
    }

    fetchUserInfo()
  }, [])

  useEffect(() => {
    let cancelled = false

    const fetchUnits = async () => {
      try {
        const response = await fetch(apiUrl('/api/company-co/assigned-units'), {
          method: 'GET',
          credentials: 'include',
        })
        const data = await response.json()

        if (!cancelled && response.ok && data.success) {
          const units = Array.isArray(data.units) ? data.units : []
          setUnitOptions(units)
          setFormData((prev) => ({
            ...prev,
            unit_id: prev.unit_id || units[0]?.unit_id || '',
          }))
        }
      } catch (error) {
        console.error('Error fetching coordinator units:', error)
        if (!cancelled) {
          setUnitOptions([])
        }
      }
    }

    fetchUnits()

    return () => {
      cancelled = true
    }
  }, [])

  useEffect(() => {
    let cancelled = false
    const unitId = String(formData.unit_id || '').trim()

    if (!unitId) {
      setUnitSampleSizeSettings([])
      return undefined
    }

    const fetchUnitSampleSizeSettings = async () => {
      try {
        const response = await fetch(
          apiUrl(`/api/company-co/unit-sample-size-config?unit_id=${encodeURIComponent(unitId)}`),
          { credentials: 'include' }
        )
        const data = await response.json()
        if (cancelled) return
        if (response.ok && data.success) {
          setUnitSampleSizeSettings(Array.isArray(data.data?.settings) ? data.data.settings : [])
        } else {
          setUnitSampleSizeSettings([])
        }
      } catch (error) {
        console.error('Error fetching unit sample size settings:', error)
        if (!cancelled) {
          setUnitSampleSizeSettings([])
        }
      }
    }

    fetchUnitSampleSizeSettings()

    return () => {
      cancelled = true
    }
  }, [formData.unit_id])

  useEffect(() => {
    let cancelled = false
    const unitId = String(formData.unit_id || '').trim()

    if (!unitId) {
      setRacmTemplate(null)
      setExtraTemplateFields([])
      setDynamicValues({})
      setSectionLabels(DEFAULT_SECTION_LABELS)
      return undefined
    }

    const fetchActiveTemplate = async () => {
      setTemplateLoading(true)
      try {
        const response = await fetch(
          apiUrl(`/api/company-co/racm-templates?unit_id=${encodeURIComponent(unitId)}`),
          { credentials: 'include' }
        )
        const data = await response.json()
        if (cancelled) return

        if (response.ok && data.success) {
          const extras = Array.isArray(data.data?.extra_fields) ? data.data.extra_fields : []
          setRacmTemplate(data.data?.template || null)
          setExtraTemplateFields(extras)
          setSectionLabels({
            ...DEFAULT_SECTION_LABELS,
            ...(data.data?.section_labels || {}),
          })
          setDynamicValues((prev) => {
            const next = {}
            extras.forEach((field) => {
              next[field.field_key] = prev[field.field_key] || ''
            })
            return next
          })
        } else {
          setRacmTemplate(null)
          setExtraTemplateFields([])
          setDynamicValues({})
        }
      } catch (error) {
        console.error('Error fetching active RACM template:', error)
        if (!cancelled) {
          setRacmTemplate(null)
          setExtraTemplateFields([])
          setDynamicValues({})
        }
      } finally {
        if (!cancelled) {
          setTemplateLoading(false)
        }
      }
    }

    fetchActiveTemplate()

    return () => {
      cancelled = true
    }
  }, [formData.unit_id])

  const groupedExtraTemplateFields = useMemo(() => {
    const groups = {}
    extraTemplateFields.forEach((field) => {
      const sectionKey = field.section_key || 'others'
      if (!groups[sectionKey]) {
        groups[sectionKey] = []
      }
      groups[sectionKey].push(field)
    })
    Object.values(groups).forEach((fields) => {
      fields.sort((a, b) => (a.display_order || 0) - (b.display_order || 0))
    })
    return groups
  }, [extraTemplateFields])

  const assertionTemplateFields = groupedExtraTemplateFields.assertions || []
  const othersTemplateFields = groupedExtraTemplateFields.others || []

  const handleDynamicFieldChange = useCallback((fieldKey, value) => {
    setDynamicValues((prev) => ({
      ...prev,
      [fieldKey]: value,
    }))
  }, [])

  const getControlFrequencySampleSizeMeta = useCallback(
    (frequencyLabel) => getEffectiveSampleSizeForFrequency(unitSampleSizeSettings, frequencyLabel),
    [unitSampleSizeSettings]
  )

  const formatControlFrequencySampleSizeLabel = useCallback(
    (frequencyLabel) => {
      const meta = getControlFrequencySampleSizeMeta(frequencyLabel)
      if (meta.sampleSize == null) return frequencyLabel
      return `${frequencyLabel} (Sample size: ${meta.sampleSize})`
    },
    [getControlFrequencySampleSizeMeta]
  )

  const resetFormAfterSubmit = useCallback(() => {
    const defaultUnitId = unitOptions[0]?.unit_id || ''
    setFormData(createEmptyFormData(defaultUnitId))
    setDropdownSelections({})
    setOtherValues({})
    setControlNumberMeta(EMPTY_CONTROL_NUMBER_META)
    setAssignmentSectionKey((current) => current + 1)
    setDynamicValues({})
  }, [unitOptions])

  useEffect(() => {
    return () => {
      if (controlNumberDebounceRef.current) {
        clearTimeout(controlNumberDebounceRef.current)
      }
    }
  }, [])

  const checkControlNumberPreview = useCallback(async ({ businessProcess, controlNumber }) => {
    if (!companyIdentifier) return { generated: '', duplicate: false }
    const params = new URLSearchParams({
      company_identifier: companyIdentifier,
    })
    if (businessProcess) params.set('business_process', businessProcess)
    if (controlNumber) params.set('control_number', controlNumber)
    const response = await fetch(`${API_BASE_URL}/api/control-forms/control-number-preview?${params.toString()}`, {
      credentials: 'include',
    })
    const result = await response.json()
    if (!response.ok || !result?.success) {
      throw new Error(result?.message || 'Failed to check control number')
    }
    return {
      generated: String(result.data?.generated_control_number || '').trim(),
      duplicate: !!result.data?.duplicate,
    }
  }, [companyIdentifier])

  const handleChange = (e) => {
    const { name, value } = e.target

    if (name === 'unit_id') {
      const previousUnitId = String(formData.unit_id || '').trim()
      const nextUnitId = String(value || '').trim()
      if (previousUnitId !== nextUnitId) {
        setFormData((prev) => ({
          ...prev,
          unit_id: value,
          control_owner: '',
          control_performer: '',
          control_frequency: '',
          sample_size: '',
        }))
        setDropdownSelections((prev) => ({
          ...prev,
          control_frequency: '',
        }))
        setDynamicValues({})
        return
      }
    }

    if (Object.prototype.hasOwnProperty.call(dynamicValues, name)) {
      setDynamicValues((prev) => ({
        ...prev,
        [name]: value,
      }))
      return
    }

    setFormData(prev => ({
      ...prev,
      [name]: value
    }))

    if (name === 'control_number') {
      setControlNumberMeta((prev) => ({
        ...prev,
        autoGenerated: false,
        duplicate: false,
        available: false,
      }))
      if (controlNumberDebounceRef.current) {
        clearTimeout(controlNumberDebounceRef.current)
      }
      const trimmed = String(value || '').trim()
      if (!trimmed || !companyIdentifier) {
        setControlNumberMeta((prev) => ({
          ...prev,
          checkingDuplicate: false,
          duplicate: false,
          available: false,
        }))
        return
      }
      controlNumberDebounceRef.current = setTimeout(async () => {
        setControlNumberMeta((prev) => ({ ...prev, checkingDuplicate: true }))
        try {
          const preview = await checkControlNumberPreview({
            businessProcess: formData.business_process,
            controlNumber: trimmed,
          })
          setControlNumberMeta((prev) => ({
            ...prev,
            checkingDuplicate: false,
            duplicate: preview.duplicate,
            available: !preview.duplicate,
          }))
        } catch (error) {
          console.error('Control number duplicate check error:', error)
          setControlNumberMeta((prev) => ({
            ...prev,
            checkingDuplicate: false,
            available: false,
          }))
        }
      }, 300)
    }
  }

  const handleGenerateControlNumber = async () => {
    const selectedProcess = String(formData.business_process || '').trim()
    if (!selectedProcess) {
      toast.error('Please select a business process first')
      return
    }
    if (!companyIdentifier) return

    setControlNumberMeta((prev) => ({
      ...prev,
      checkingDuplicate: true,
      duplicate: false,
      available: false,
    }))
    try {
      const preview = await checkControlNumberPreview({
        businessProcess: selectedProcess,
        controlNumber: '',
      })
      if (!preview.generated) {
        toast.error('Unable to generate Control Number')
        setControlNumberMeta((prev) => ({ ...prev, checkingDuplicate: false }))
        return
      }

      setFormData((prev) => ({
        ...prev,
        control_number: preview.generated,
      }))

      const generatedCheck = await checkControlNumberPreview({
        businessProcess: selectedProcess,
        controlNumber: preview.generated,
      })
      setControlNumberMeta((prev) => ({
        ...prev,
        autoGenerated: true,
        checkingDuplicate: false,
        duplicate: generatedCheck.duplicate,
        available: !generatedCheck.duplicate,
      }))
    } catch (error) {
      console.error('Control number generate error:', error)
      setControlNumberMeta((prev) => ({
        ...prev,
        checkingDuplicate: false,
        available: false,
      }))
      toast.error('Failed to generate Control Number')
    }
  }

  const handleDropdownChange = (field, value) => {
    setDropdownSelections((prev) => ({
      ...prev,
      [field]: value
    }))

    if (value === 'Other') {
      setFormData((prev) => ({
        ...prev,
        [field]: otherValues[field] || ''
      }))
      return
    }

    if (field === 'control_frequency') {
      const meta = getControlFrequencySampleSizeMeta(value)
      setFormData((prev) => ({
        ...prev,
        [field]: value,
        sample_size: meta.sampleSize != null ? String(meta.sampleSize) : '',
      }))
      return
    }

    setFormData((prev) => ({
      ...prev,
      [field]: value
    }))
  }

  const handleOtherValueChange = (field, value) => {
    setOtherValues((prev) => ({
      ...prev,
      [field]: value
    }))

    if (dropdownSelections[field] === 'Other') {
      setFormData((prev) => ({
        ...prev,
        [field]: value
      }))
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()

    if (!formData.business_process) {
      toast.error('Please select a business process')
      return
    }

    if (!formData.financial_year) {
      toast.error('Please select a financial year')
      return
    }

    if (!formData.unit_id) {
      toast.error('Please select a unit')
      return
    }

    if (!String(formData.control_frequency || '').trim()) {
      toast.error('Please select frequency of control')
      return
    }

    const frequency = String(formData.control_frequency || '').trim()
    const sampleSizeValue = String(formData.sample_size || '').trim()
    if (!sampleSizeValue) {
      toast.error('Please enter sample size')
      return
    }

    const sampleValidation = validateSampleSizeForFrequency(
      unitSampleSizeSettings,
      frequency,
      sampleSizeValue
    )
    if (!sampleValidation.ok) {
      toast.error(sampleValidation.message)
      return
    }

    const dueDateValue = String(formData.due_date || '').trim()
    const reminderFrequencyValue = String(formData.reminder_frequency || '').trim()
    if ((dueDateValue && !reminderFrequencyValue) || (!dueDateValue && reminderFrequencyValue)) {
      toast.error('Please fill both Due Date and Reminder Frequency (or keep both empty).')
      return
    }

    if (controlNumberMeta.duplicate) {
      toast.error('Control Number already exists. Please choose another one.')
      return
    }

    setLoading(true)

    try {
      const response = await fetch(apiUrl('/api/control-forms'), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify({
          ...formData,
          company_identifier: companyIdentifier,
          dynamic_values: dynamicValues,
        })
      })

      const data = await response.json()

      if (response.ok && data.success) {
        toast.success(data.message || 'RACM created successfully')
        resetFormAfterSubmit()
      } else if (response.status === 409) {
        toast.error(data.message || 'Duplicate RACM already exists.')
      } else {
        toast.error(data.message || 'Failed to create RACM')
      }
    } catch (err) {
      console.error('Create form error:', err)
      toast.error('Network error. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  // Fields that need multiline (text areas)
  const multilineFields = [
    'standard_control_description',
    'risk_description',
    'control_objective',
    'process_walkthrough',
    'audit_evidence_accuracy',
    'ipe_reference'
  ]

  // Field labels
  const fieldLabels = {
  business_process: 'Business Process',
  financial_year: 'Financial Year',
  unit_id: 'Unit',
  control_number: 'Control Number (Auto-generated if left empty)',
  area: 'Area',
  risk_heat: 'Risk Heat',
  standard_control_description: 'Standard Control Description',
  sub_process: 'Sub Process',
  risk_description: 'Risk Description',
  control_objective: 'Control Objective',
  process_walkthrough: 'Process activity and walkthrough details',
  control_relies_on_ipe: 'Does the control rely on information produced by the entity?',
  audit_evidence_accuracy: 'Will we obtain audit evidence of the accuracy and completeness of information produced by the entity by testing controls or by performing procedures directly on the information?',
  ipe_reference: 'IPE Reference',
  key_control: 'Key Control (Yes / No)',
  application_name: 'Application Name',
  control_performer: 'Control Performer',
  control_owner: 'Process Owner',
  control_type_fo: 'Type of control (Operational/Financial)',
  control_type_ma: 'Type of control (Manual/ Automated)',
  nature_of_control: 'Nature of Control (Preventive or Detective)',
  control_frequency: 'Frequency of Control',
  sample_size: 'Sample Size',
  whether_fraud_risks_exist: 'Whether fraud risk exists?',
  }

  // Exact display order requested for Control section (frontend-only ordering/wording)
  const controlSectionFieldOrder = [
    'control_objective',
    'standard_control_description',
    'process_walkthrough',
    'control_type_fo',
    'control_relies_on_ipe',
    'ipe_reference',
    'audit_evidence_accuracy',
    'nature_of_control',
    'control_type_ma',
    'key_control',
    'application_name',
    'control_frequency',
    'sample_size',
    'whether_fraud_risks_exist',
  ]

  const selectedUnitLabel = useMemo(() => {
    const unit = unitOptions.find((option) => option.unit_id === formData.unit_id)
    return unit?.unit_name || formData.unit_id || 'this unit'
  }, [unitOptions, formData.unit_id])

  const racmTemplatesHref = formData.unit_id
    ? `/company_co/racm-templates?unit_id=${encodeURIComponent(formData.unit_id)}`
    : '/company_co/racm-templates'

  return (
    <Box 
      sx={{ 
        width: '100%',
        maxWidth: FORM_DETAIL_MAX_WIDTH,
        mx: 'auto',
        px: 0, 
        py: 0,
      }}
    >
      <Box sx={{ width: '100%' }}>
        <Paper 
          elevation={3}
          sx={{
            p: 4,
            backgroundColor: theme.palette.background.paper,
            borderRadius: 2,
          }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
            <IconButton
              onClick={() => navigate('/company_co/control-creation')}
              sx={{
                mr: 2,
                color: theme.palette.text.primary,
                '&:hover': {
                  backgroundColor: theme.palette.mode === 'dark' 
                    ? 'rgba(255, 255, 255, 0.08)' 
                    : 'rgba(0, 0, 0, 0.04)',
                },
              }}
              aria-label="back to dashboard"
            >
              <ArrowBackIcon />
            </IconButton>
            <Typography
              variant="h4"
              component="h1"
              sx={{
                fontWeight: 700,
                color: 'text.primary',
                flex: 1,
                letterSpacing: '-0.02em',
                position: 'relative',
                pl: { xs: 0, sm: 1.75 },
              }}
            >
              Create RACM
            </Typography>
            <IconButton
              onClick={() => setTemplateHelpDialogOpen(true)}
              aria-label="Template column help"
              sx={{
                color: 'text.secondary',
                '&:hover': {
                  color: 'primary.main',
                  backgroundColor: theme.palette.mode === 'dark'
                    ? 'rgba(255, 255, 255, 0.08)'
                    : 'rgba(0, 0, 0, 0.04)',
                },
              }}
            >
              <LightbulbOutlinedIcon />
            </IconButton>
          </Box>

          <form onSubmit={handleSubmit}>
            {/* Top section: Business Process, Financial Year & Unit */}
            <Box
              sx={{
                mb: 4,
                display: 'grid',
                gridTemplateColumns: {
                  xs: '1fr',
                  md: 'repeat(3, 1fr)',
                },
                gap: 3,
              }}
            >
              {['business_process', 'financial_year', 'unit_id'].map((field) => {
                const label = fieldLabels[field]
                const value = formData[field] || ''
                const options =
                  field === 'business_process'
                    ? businessProcessOptions
                    : field === 'financial_year'
                      ? financialYearOptions
                      : unitOptions

                return (
                  <FormControl
                    key={field}
                    fullWidth
                    required
                  >
                    <InputLabel id={`${field}-label`}>{label}</InputLabel>
                    <Select
                      labelId={`${field}-label`}
                      id={field}
                      name={field}
                      value={value}
                      label={label}
                      onChange={async (e) => {
                        handleChange(e)
                        if (field !== 'business_process') return
                        const selectedProcess = String(e.target.value || '').trim()
                        if (!selectedProcess || !companyIdentifier) return
                        try {
                          const preview = await checkControlNumberPreview({
                            businessProcess: selectedProcess,
                            controlNumber: '',
                          })
                          if (!preview.generated) return
                          setFormData((prev) => {
                            const currentCn = String(prev.control_number || '').trim()
                            if (!currentCn || controlNumberMeta.autoGenerated) {
                              return { ...prev, control_number: preview.generated }
                            }
                            return prev
                          })
                          setControlNumberMeta((prev) => ({
                            ...prev,
                            autoGenerated: true,
                            duplicate: false,
                            available: false,
                          }))
                        } catch (error) {
                          console.error('Control number auto-generation error:', error)
                        }
                      }}
                      variant="outlined"
                      disabled={
                        loading ||
                        (field === 'unit_id' && unitOptions.length === 0) ||
                        (field === 'business_process' && businessProcessesLoading)
                      }
                    >
                      {options.map((option) => (
                        <MenuItem
                          key={field === 'unit_id' ? option.unit_id || option.id : option}
                          value={field === 'unit_id' ? option.unit_id : option}
                        >
                          {field === 'unit_id' ? option.unit_name || option.unit_id : option}
                        </MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                )
              })}
            </Box>

            <ActiveRacmTemplateNotice
              unitId={formData.unit_id}
              variant="manual"
              useParentSummary
              templateSummary={
                racmTemplate
                  ? {
                      templateName: racmTemplate.template_name,
                      version: racmTemplate.version,
                      extraFieldCount: extraTemplateFields.length,
                    }
                  : null
              }
              sx={{ mb: extraTemplateFields.length > 0 ? 2 : 4 }}
            />

            {extraTemplateFields.length > 0 ? (
              <Stack
                direction="row"
                alignItems="center"
                spacing={0.75}
                sx={{ mb: 4 }}
              >
                <CustomColumnDot />
                <Typography variant="caption" color="text.secondary">
                  Fields marked with a yellow dot are custom columns from your unit template.
                </Typography>
              </Stack>
            ) : null}

            {/* Process and risk section */}
            <Box
              sx={{
                mb: 4,
                borderTop: '2px solid',
                borderColor: 'divider',
                pt: 3,
              }}
            >
              <Typography
                variant="h6"
                component="h2"
                sx={{
                  fontWeight: 700,
                  mb: 3,
                  color: 'text.primary',
                  fontSize: '1.125rem',
                }}
              >
                Process and risk
              </Typography>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: {
                    xs: '1fr',
                    md: 'repeat(2, 1fr)',
                  },
                  gap: 3,
                }}
              >
                {['control_number', 'area', 'sub_process', 'risk_heat', 'risk_description'].map((field) => {
                  const label = fieldLabels[field]
                  const value = formData[field] || ''
                  const isMultiline = multilineFields.includes(field)
                  const isConfiguredDropdown = Object.prototype.hasOwnProperty.call(dropdownOptions, field)

                  if (isConfiguredDropdown) {
                    const options = dropdownOptions[field]
                    const selectedValue = dropdownSelections[field] || (options.includes(value) ? value : '')
                    const isOtherSelected = selectedValue === 'Other'

                    return (
                      <Box key={field}>
                        <FormControl fullWidth disabled={loading}>
                          <InputLabel id={`${field}-label`}>{label}</InputLabel>
                          <Select
                            labelId={`${field}-label`}
                            id={field}
                            name={field}
                            value={selectedValue}
                            label={label}
                            onChange={(e) => handleDropdownChange(field, e.target.value)}
                            variant="outlined"
                          >
                            {options.map((option) => (
                              <MenuItem key={option} value={option}>
                                {option}
                              </MenuItem>
                            ))}
                          </Select>
                        </FormControl>
                        {isOtherSelected && (
                          <TextField
                            sx={{ mt: 1.5 }}
                            fullWidth
                            label={`${label} (Other)`}
                            value={otherValues[field] || value || ''}
                            onChange={(e) => handleOtherValueChange(field, e.target.value)}
                            disabled={loading}
                          />
                        )}
                      </Box>
                    )
                  }

                  return (
                    <TextField
                      key={field}
                      name={field}
                      label={label}
                      value={value}
                      onChange={handleChange}
                      fullWidth
                      multiline={isMultiline}
                      rows={isMultiline ? 4 : 1}
                      variant="outlined"
                      disabled={loading}
                      sx={{
                        gridColumn: isMultiline
                          ? {
                              xs: '1',
                              md: '1 / -1',
                            }
                          : undefined,
                      }}
                    />
                  )
                })}
                <RacmTemplateSectionFields
                  blendIntoParent
                  showCustomColumnIndicator
                  sectionKey="process_and_risk"
                  fieldDefinitions={extraTemplateFields}
                  values={dynamicValues}
                  isEditMode
                  onChange={handleDynamicFieldChange}
                  disabled={loading || templateLoading}
                />
              </Box>
            </Box>

            {assertionTemplateFields.length > 0 ? (
              <Box
                sx={{
                  mb: 4,
                  borderTop: '2px solid',
                  borderColor: 'divider',
                  pt: 3,
                }}
              >
                <Typography
                  variant="h6"
                  component="h2"
                  sx={{
                    fontWeight: 700,
                    mb: 3,
                    color: 'text.primary',
                    fontSize: '1.125rem',
                  }}
                >
                  {sectionLabels.assertions || 'Assertions'}
                </Typography>
                <Box
                  sx={{
                    display: 'grid',
                    gridTemplateColumns: {
                      xs: '1fr',
                      md: 'repeat(2, 1fr)',
                    },
                    gap: 3,
                  }}
                >
                  <RacmTemplateSectionFields
                    blendIntoParent
                    showCustomColumnIndicator
                    sectionKey="assertions"
                    fieldDefinitions={extraTemplateFields}
                    values={dynamicValues}
                    isEditMode
                    onChange={handleDynamicFieldChange}
                    disabled={loading || templateLoading}
                  />
                </Box>
              </Box>
            ) : null}

            {/* Remaining fields section – Control */}
            <Box
              sx={{
                borderTop: '2px solid',
                borderColor: 'divider',
                pt: 3,
                mb: 3,
              }}
            >
              <Typography
                variant="h6"
                component="h2"
                sx={{
                  fontWeight: 700,
                  mb: 3,
                  color: 'text.primary',
                  fontSize: '1.125rem',
                }}
              >
                Control Details
              </Typography>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: {
                    xs: '1fr',
                    md: 'repeat(2, 1fr)',
                  },
                  gap: 3,
                }}
              >
                {controlSectionFieldOrder
                  .map((field) => {
                    const label = fieldLabels[field] || field.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase())
                    const value = formData[field] || ''
                    const isMultiline = multilineFields.includes(field)
                    const isConfiguredDropdown = Object.prototype.hasOwnProperty.call(dropdownOptions, field)
                    const sampleSizeFrequencyMeta = field === 'sample_size'
                      ? getControlFrequencySampleSizeMeta(formData.control_frequency)
                      : null

                    if (isConfiguredDropdown) {
                      const options = dropdownOptions[field]
                      const selectedValue = dropdownSelections[field] || (options.includes(value) ? value : '')
                      const isOtherSelected = selectedValue === 'Other'

                      return (
                        <Box key={field}>
                          <FormControl
                            fullWidth
                            required={field === 'control_frequency'}
                            disabled={loading}
                          >
                            <InputLabel id={`${field}-label`}>{label}</InputLabel>
                            <Select
                              labelId={`${field}-label`}
                              id={field}
                              name={field}
                              value={selectedValue}
                              label={label}
                              onChange={(e) => handleDropdownChange(field, e.target.value)}
                              variant="outlined"
                              required={field === 'control_frequency'}
                            >
                              {options.map((option) => (
                                <MenuItem key={option} value={option}>
                                  {field === 'control_frequency'
                                    ? formatControlFrequencySampleSizeLabel(option)
                                    : option}
                                </MenuItem>
                              ))}
                            </Select>
                          </FormControl>
                          {isOtherSelected && (
                            <TextField
                              sx={{ mt: 1.5 }}
                              fullWidth
                              label={`${label} (Other)`}
                              value={otherValues[field] || value || ''}
                              onChange={(e) => handleOtherValueChange(field, e.target.value)}
                              disabled={loading}
                            />
                          )}
                        </Box>
                      )
                    }

                    if (field === 'sample_size') {
                      return (
                        <TextField
                          key={field}
                          name={field}
                          label={label}
                          value={formData.sample_size || ''}
                          onChange={handleChange}
                          fullWidth
                          type="number"
                          variant="outlined"
                          disabled={loading || !String(formData.control_frequency || '').trim()}
                          required
                          inputProps={{
                            min: sampleSizeFrequencyMeta?.minimum ?? 1,
                            step: 1,
                          }}
                          helperText={
                            !String(formData.control_frequency || '').trim()
                              ? 'Select frequency of control first'
                              : (sampleSizeFrequencyMeta?.minimum != null
                                ? `Minimum sample size: ${sampleSizeFrequencyMeta.minimum}`
                                : undefined)
                          }
                        />
                      )
                    }

                    return (
                      <TextField
                        key={field}
                        name={field}
                        label={field === 'control_number' && controlNumberMeta.autoGenerated
                          ? `${label} (auto-generated)`
                          : label}
                        value={value}
                        onChange={handleChange}
                        fullWidth
                        multiline={isMultiline}
                        rows={isMultiline ? 4 : 1}
                        variant="outlined"
                        disabled={loading}
                        error={field === 'control_number' && controlNumberMeta.duplicate}
                        helperText={field === 'control_number' && controlNumberMeta.duplicate
                          ? 'Control Number already exists'
                          : (field === 'control_number' && controlNumberMeta.available
                            ? 'Control Number is available'
                            : (field === 'control_number'
                              ? 'Control number will be generated automatically if left empty'
                              : undefined))}
                        FormHelperTextProps={{
                          sx: field === 'control_number' && controlNumberMeta.available
                            ? { color: 'success.main' }
                            : undefined,
                        }}
                        InputProps={{
                          endAdornment: field === 'control_number' ? (
                            <InputAdornment position="end" sx={{ gap: 1 }}>
                              {controlNumberMeta.checkingDuplicate ? 'Checking...' : null}
                              <Button
                                size="small"
                                variant="text"
                                disabled={loading || businessProcessesLoading || controlNumberMeta.checkingDuplicate}
                                onMouseDown={(event) => event.preventDefault()}
                                onClick={handleGenerateControlNumber}
                                sx={{ minWidth: 'auto', px: 1, textTransform: 'none', fontWeight: 700 }}
                              >
                                Generate
                              </Button>
                            </InputAdornment>
                          ) : undefined,
                        }}
                        sx={{
                          gridColumn: isMultiline
                            ? {
                                xs: '1',
                                md: '1 / -1',
                              }
                            : undefined,
                        }}
                      />
                    )
                  })}
                <RacmTemplateSectionFields
                  blendIntoParent
                  showCustomColumnIndicator
                  sectionKey="control_details"
                  fieldDefinitions={extraTemplateFields}
                  values={dynamicValues}
                  isEditMode
                  onChange={handleDynamicFieldChange}
                  disabled={loading || templateLoading}
                />
              </Box>
            </Box>

            {othersTemplateFields.length > 0 ? (
              <Box
                sx={{
                  borderTop: '2px solid',
                  borderColor: 'divider',
                  pt: 3,
                  mb: 3,
                }}
              >
                <Typography
                  variant="h6"
                  component="h2"
                  sx={{
                    fontWeight: 700,
                    mb: 3,
                    color: 'text.primary',
                    fontSize: '1.125rem',
                  }}
                >
                  {sectionLabels.others || 'Others'}
                </Typography>
                <Box
                  sx={{
                    display: 'grid',
                    gridTemplateColumns: {
                      xs: '1fr',
                      md: 'repeat(2, 1fr)',
                    },
                    gap: 3,
                  }}
                >
                  <RacmTemplateSectionFields
                    blendIntoParent
                    showCustomColumnIndicator
                    sectionKey="others"
                    fieldDefinitions={extraTemplateFields}
                    values={dynamicValues}
                    isEditMode
                    onChange={handleDynamicFieldChange}
                    disabled={loading || templateLoading}
                  />
                </Box>
              </Box>
            ) : null}

            <RacmUserAssignmentSection
              key={`${formData.unit_id || 'no-unit'}-${assignmentSectionKey}`}
              unitId={formData.unit_id}
              controlOwner={formData.control_owner}
              controlPerformer={formData.control_performer}
              onControlOwnerChange={(email) =>
                setFormData((prev) => ({ ...prev, control_owner: email }))
              }
              onControlPerformerChange={(email) =>
                setFormData((prev) => ({ ...prev, control_performer: email }))
              }
              loading={loading}
            />

            {/* Reminder settings section */}
            <Paper
              elevation={0}
              sx={{
                p: { xs: 2, sm: 2.2 },
                mb: 3,
                borderRadius: 2,
                border: '1px solid',
                borderColor:
                  theme.palette.mode === 'dark'
                    ? 'rgba(255, 255, 255, 0.07)'
                    : theme.palette.divider,
                backgroundColor: theme.palette.mode === 'dark'
                  ? 'rgba(255, 255, 255, 0.025)'
                  : '#f8fafc',
              }}
            >
              <Box
                sx={{
                  display: 'flex',
                  alignItems: 'center',
                  flexWrap: 'wrap',
                  gap: 1.1,
                  rowGap: 1,
                  mb: 1.8,
                }}
              >
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.1, flex: 1, minWidth: 0 }}>
                  <ChecklistRoundedIcon sx={{ fontSize: 20, color: theme.palette.text.secondary }} />
                  <Typography sx={{ fontSize: '1rem', fontWeight: 800, color: theme.palette.text.primary }}>
                    Reminder settings
                  </Typography>
                  <Typography sx={{ fontSize: '0.86rem', color: theme.palette.text.secondary }}>
                    Optional
                  </Typography>
                </Box>
                <Button
                  type="button"
                  variant="outlined"
                  size="small"
                  onClick={handleResetReminderSettings}
                  disabled={loading || !hasReminderValues}
                  sx={{
                    textTransform: 'none',
                    borderRadius: 2,
                    ml: { xs: 'auto', sm: 0 },
                  }}
                >
                  Reset
                </Button>
              </Box>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' },
                  gap: 2,
                }}
              >
                <LocalizationProvider dateAdapter={AdapterDayjs}>
                  <DatePicker
                    label="Due Date"
                    value={formData.due_date ? dayjs(formData.due_date) : null}
                    onChange={(newValue) => {
                      if (!newValue || !newValue.isValid()) {
                        setFormData((prev) => ({ ...prev, due_date: '' }))
                        return
                      }
                      setFormData((prev) => ({ ...prev, due_date: newValue.format('YYYY-MM-DD') }))
                    }}
                    minDate={dayjs(getTomorrowDateString())}
                    disabled={loading}
                    slotProps={{
                      textField: {
                        fullWidth: true,
                      },
                    }}
                  />
                </LocalizationProvider>

                <FormControl fullWidth disabled={loading} variant="outlined">
                  <InputLabel id="manual-reminder-frequency-label">Reminder Frequency</InputLabel>
                  <Select
                    labelId="manual-reminder-frequency-label"
                    value={formData.reminder_frequency}
                    label="Reminder Frequency"
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        reminder_frequency: e.target.value,
                      }))
                    }
                  >
                    <MenuItem value="Daily">Daily</MenuItem>
                    <MenuItem value="Weekly">Weekly</MenuItem>
                    <MenuItem value="Monthly">Monthly</MenuItem>
                  </Select>
                </FormControl>
              </Box>
            </Paper>

            {/* Submit Button */}
            <Box sx={{ display: 'flex', gap: 2, mt: 4, flexWrap: 'wrap' }}>
              <Button
                type="submit"
                disabled={
                  loading ||
                  businessProcessesLoading ||
                  !formData.business_process ||
                  !formData.financial_year ||
                  !formData.unit_id ||
                  !String(formData.control_frequency || '').trim() ||
                  !String(formData.sample_size || '').trim()
                }
                variant="contained"
                color="secondary"
                sx={{
                  py: 1.5,
                  px: 3,
                  minWidth: 180,
                  fontSize: theme.typography.customSizes.medium,
                  fontWeight: 600,
                  textTransform: 'none',
                }}
              >
                {loading ? 'Creating...' : 'Create RACM'}
              </Button>
            </Box>
          </form>
        </Paper>
      </Box>

      <AppDialog
        open={templateHelpDialogOpen}
        onClose={() => setTemplateHelpDialogOpen(false)}
        title="Missing columns on this form?"
        actions={
          <Button
            variant="contained"
            onClick={() => setTemplateHelpDialogOpen(false)}
            sx={APP_DIALOG_PRIMARY_BUTTON_SX}
          >
            Close
          </Button>
        }
      >
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          This form follows the active RACM template for{' '}
          <strong>{selectedUnitLabel}</strong>. If you need additional fields, edit that template
          to add or adjust columns, then return here to create RACMs with the updated layout.
        </Typography>
        <Link
          component={RouterLink}
          to={racmTemplatesHref}
          onClick={() => setTemplateHelpDialogOpen(false)}
          sx={{ fontWeight: 600 }}
        >
          Open RACM Templates
        </Link>
      </AppDialog>
    </Box>
  )
}

export default CreateControlForm
