import React, { useState, useEffect, useCallback, useRef } from 'react'
import { useTheme } from '@mui/material/styles'
import { useNavigate } from 'react-router-dom'
import Button from '@mui/material/Button'
import Box from '@mui/material/Box'
import Paper from '@mui/material/Paper'
import Typography from '@mui/material/Typography'
import TextField from '@mui/material/TextField'
import MenuItem from '@mui/material/MenuItem'
import FormControl from '@mui/material/FormControl'
import InputLabel from '@mui/material/InputLabel'
import Select from '@mui/material/Select'
import IconButton from '@mui/material/IconButton'
import Checkbox from '@mui/material/Checkbox'
import Autocomplete from '@mui/material/Autocomplete'
import InputAdornment from '@mui/material/InputAdornment'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import { toast } from 'react-hot-toast'
import { FORM_DETAIL_MAX_WIDTH } from '../../uiConstants'
import { apiUrl, API_BASE_URL } from '../../config/api'
import { useBusinessProcesses } from '../../hooks/useBusinessProcesses'

const ASSIGNABLE_USER_INITIAL_LIMIT = 5
const ASSIGNABLE_USER_SEARCH_LIMIT = 50

/** Ensures the current selection is present in options (avoids MUI warnings when the list was refetched). Same user may be both owner and performer — no exclusion. */
function mergeAssignableUserIntoOptions(options, selectedEmail) {
  const email = (selectedEmail || '').trim()
  if (!email) return options
  const lower = email.toLowerCase()
  if (options.some((u) => (u.email_id || '').trim().toLowerCase() === lower)) {
    return options
  }
  return [...options, { email_id: email, emp_name: '' }]
}

function CreateControlForm() {
  const theme = useTheme()
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [companyIdentifier, setCompanyIdentifier] = useState('')
  const [unitOptions, setUnitOptions] = useState([])
  const [ownerOptions, setOwnerOptions] = useState([])
  const [usersLoading, setUsersLoading] = useState(false)
  const assignableUserSearchDebounceRef = useRef(null)
  const controlNumberDebounceRef = useRef(null)
  const { businessProcessOptions, loading: businessProcessesLoading } = useBusinessProcesses()
  const [controlNumberMeta, setControlNumberMeta] = useState({
    autoGenerated: false,
    checkingDuplicate: false,
    duplicate: false,
    available: false,
  })

  const fetchAssignableUsers = useCallback(
    async ({ q = '', limit = ASSIGNABLE_USER_INITIAL_LIMIT } = {}) => {
      if (!companyIdentifier) return
      setUsersLoading(true)
      try {
        const params = new URLSearchParams({
          role: 'user',
          limit: String(limit),
        })
        const trimmedQ = String(q || '').trim()
        if (trimmedQ) {
          params.set('q', trimmedQ)
        }
        const response = await fetch(
          `${API_BASE_URL}/api/company-co/users?${params.toString()}`,
          {
            method: 'GET',
            credentials: 'include',
          }
        )
        const data = await response.json()
        if (response.ok && data.success) {
          setOwnerOptions(Array.isArray(data.users) ? data.users : [])
        } else {
          setOwnerOptions([])
        }
      } catch (error) {
        console.error('Error fetching company users:', error)
        setOwnerOptions([])
      } finally {
        setUsersLoading(false)
      }
    },
    [companyIdentifier]
  )

  // Financial year options - dynamically based on current year
  // Example: if current year is 2026 -> [ '2025-26', '2026-27' ]
  const currentYear = new Date().getFullYear()
  const baseFYStart = currentYear - 1
  const financialYearOptions = Array.from({ length: 2 }, (_, i) => {
    const startYear = baseFYStart + i
    const endYearShort = String((startYear + 1) % 100).padStart(2, '0')
    return `${startYear}-${endYearShort}`
  })

  // Form state - all fields that coordinators can create
  const [formData, setFormData] = useState({
    business_process: '',
    financial_year: '',
    unit_id: '',
    control_number: '',
    area: '',
    risk_heat: '',
    standard_control_description: '',
    sub_process: '',
    risk_description: '',
    whether_fraud_risks_exist: '',
    control_objective: '',
    process_walkthrough: '',
    control_relies_on_ipe: '',
    audit_evidence_accuracy: '',
    ipe_reference: '',
    key_control: '',
    application_name: '',
    control_performer: '',
    control_owner: '',
    control_type_fo: '',
    control_type_ma: '',
    nature_of_control: '',
    control_frequency: '',
    completeness: false,
    existence_occurrence: false,
    rights_and_obligation: false,
    valuation_and_allocation: false,
    presentation_and_disclosure: false
  })

  const dropdownOptions = {
  risk_heat: ['High', 'Low', 'Medium'],
  control_type_fo: ['Financial', 'Operational'],
  control_type_ma: ['Manual', 'Automated'],
  nature_of_control: ['Preventive', 'Detective'],
  key_control: ['Yes', 'No'],
  control_relies_on_ipe: ['Yes', 'No'],
    control_frequency: [
      'Yearly',
      'Quarterly',
      'Half Yearly',
      'Monthly',
      'Weekly',
      'Fortnightly',
      'As and When Needed',
      'Recurring and Daily',
    ],
    whether_fraud_risks_exist: ['Yes', 'No']
  }

  const [dropdownSelections, setDropdownSelections] = useState({})
  const [otherValues, setOtherValues] = useState({})

  useEffect(() => {
    // Fetch user's company_identifier
    const fetchUserInfo = async () => {
      try {
        const response = await fetch(apiUrl('/api/auth/verify'), {
          method: 'GET',
          credentials: 'include',
        })

        const data = await response.json()

        if (response.ok && data.success && data.user.company_identifier) {
          setCompanyIdentifier(data.user.company_identifier)
        }
      } catch (error) {
        console.error('Error fetching user info:', error)
      }
    }

    fetchUserInfo()
  }, [])

  useEffect(() => {
    if (!companyIdentifier) return
    fetchAssignableUsers({ q: '', limit: ASSIGNABLE_USER_INITIAL_LIMIT })
  }, [companyIdentifier, fetchAssignableUsers])

  useEffect(() => {
    let cancelled = false

    const fetchUnits = async () => {
      try {
        const response = await fetch(apiUrl('/api/company-co/unit-management'), {
          method: 'GET',
          credentials: 'include',
        })
        const data = await response.json()

        if (!cancelled && response.ok && data.success) {
          const units = Array.isArray(data.data?.currentCoordinatorUnits)
            ? data.data.currentCoordinatorUnits
            : []
          setUnitOptions(units)
          setFormData((prev) => ({
            ...prev,
            unit_id: prev.unit_id || units[0]?.unit_id || '',
          }))
        }
      } catch (error) {
        console.error('Error fetching coordinator units:', error)
        if (!cancelled) {
          setUnitOptions([])
        }
      }
    }

    fetchUnits()

    return () => {
      cancelled = true
    }
  }, [])

  useEffect(() => {
    return () => {
      if (assignableUserSearchDebounceRef.current) {
        clearTimeout(assignableUserSearchDebounceRef.current)
      }
      if (controlNumberDebounceRef.current) {
        clearTimeout(controlNumberDebounceRef.current)
      }
    }
  }, [])

  const checkControlNumberPreview = useCallback(async ({ businessProcess, controlNumber }) => {
    if (!companyIdentifier) return { generated: '', duplicate: false }
    const params = new URLSearchParams({
      company_identifier: companyIdentifier,
    })
    if (businessProcess) params.set('business_process', businessProcess)
    if (controlNumber) params.set('control_number', controlNumber)
    const response = await fetch(`${API_BASE_URL}/api/control-forms/control-number-preview?${params.toString()}`, {
      credentials: 'include',
    })
    const result = await response.json()
    if (!response.ok || !result?.success) {
      throw new Error(result?.message || 'Failed to check control number')
    }
    return {
      generated: String(result.data?.generated_control_number || '').trim(),
      duplicate: !!result.data?.duplicate,
    }
  }, [companyIdentifier])

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: value
    }))

    if (name === 'control_number') {
      setControlNumberMeta((prev) => ({
        ...prev,
        autoGenerated: false,
        duplicate: false,
        available: false,
      }))
      if (controlNumberDebounceRef.current) {
        clearTimeout(controlNumberDebounceRef.current)
      }
      const trimmed = String(value || '').trim()
      if (!trimmed || !companyIdentifier) {
        setControlNumberMeta((prev) => ({
          ...prev,
          checkingDuplicate: false,
          duplicate: false,
          available: false,
        }))
        return
      }
      controlNumberDebounceRef.current = setTimeout(async () => {
        setControlNumberMeta((prev) => ({ ...prev, checkingDuplicate: true }))
        try {
          const preview = await checkControlNumberPreview({
            businessProcess: formData.business_process,
            controlNumber: trimmed,
          })
          setControlNumberMeta((prev) => ({
            ...prev,
            checkingDuplicate: false,
            duplicate: preview.duplicate,
            available: !preview.duplicate,
          }))
        } catch (error) {
          console.error('Control number duplicate check error:', error)
          setControlNumberMeta((prev) => ({
            ...prev,
            checkingDuplicate: false,
            available: false,
          }))
        }
      }, 300)
    }
  }

  const handleGenerateControlNumber = async () => {
    const selectedProcess = String(formData.business_process || '').trim()
    if (!selectedProcess) {
      toast.error('Please select a business process first')
      return
    }
    if (!companyIdentifier) return

    setControlNumberMeta((prev) => ({
      ...prev,
      checkingDuplicate: true,
      duplicate: false,
      available: false,
    }))
    try {
      const preview = await checkControlNumberPreview({
        businessProcess: selectedProcess,
        controlNumber: '',
      })
      if (!preview.generated) {
        toast.error('Unable to generate Control Number')
        setControlNumberMeta((prev) => ({ ...prev, checkingDuplicate: false }))
        return
      }

      setFormData((prev) => ({
        ...prev,
        control_number: preview.generated,
      }))

      const generatedCheck = await checkControlNumberPreview({
        businessProcess: selectedProcess,
        controlNumber: preview.generated,
      })
      setControlNumberMeta((prev) => ({
        ...prev,
        autoGenerated: true,
        checkingDuplicate: false,
        duplicate: generatedCheck.duplicate,
        available: !generatedCheck.duplicate,
      }))
    } catch (error) {
      console.error('Control number generate error:', error)
      setControlNumberMeta((prev) => ({
        ...prev,
        checkingDuplicate: false,
        available: false,
      }))
      toast.error('Failed to generate Control Number')
    }
  }

  const handleAssertionToggle = (field) => (e) => {
    const checked = !!e.target.checked
    setFormData((prev) => ({
      ...prev,
      [field]: checked,
    }))
  }

  const handleDropdownChange = (field, value) => {
    setDropdownSelections((prev) => ({
      ...prev,
      [field]: value
    }))

    if (value === 'Other') {
      setFormData((prev) => ({
        ...prev,
        [field]: otherValues[field] || ''
      }))
      return
    }

    setFormData((prev) => ({
      ...prev,
      [field]: value
    }))
  }

  const handleOtherValueChange = (field, value) => {
    setOtherValues((prev) => ({
      ...prev,
      [field]: value
    }))

    if (dropdownSelections[field] === 'Other') {
      setFormData((prev) => ({
        ...prev,
        [field]: value
      }))
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()

    if (!formData.business_process) {
      toast.error('Please select a business process')
      return
    }

    if (!formData.financial_year) {
      toast.error('Please select a financial year')
      return
    }

    if (!formData.unit_id) {
      toast.error('Please select a unit')
      return
    }

    if (controlNumberMeta.duplicate) {
      toast.error('Control Number already exists. Please choose another one.')
      return
    }

    setLoading(true)

    try {
      const response = await fetch(apiUrl('/api/control-forms'), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify({
          ...formData,
          company_identifier: companyIdentifier
        })
      })

      const data = await response.json()

      if (response.ok && data.success) {
        toast.success('RACM created successfully')
        navigate('/company_co/dashboard')
      } else if (response.status === 409) {
        toast.error(data.message || 'Duplicate RACM already exists.')
      } else {
        toast.error(data.message || 'Failed to create RACM')
      }
    } catch (err) {
      console.error('Create form error:', err)
      toast.error('Network error. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  // Fields that need multiline (text areas)
  const multilineFields = [
    'standard_control_description',
    'risk_description',
    'control_objective',
    'process_walkthrough',
    'audit_evidence_accuracy',
    'ipe_reference'
  ]

  // Field labels
  const fieldLabels = {
  business_process: 'Business Process',
  financial_year: 'Financial Year',
  unit_id: 'Unit',
  control_number: 'Control Number',
  area: 'Area',
  risk_heat: 'Risk Heat',
  standard_control_description: 'Standard Control Description',
  sub_process: 'Sub Process',
  risk_description: 'Risk Description',
  control_objective: 'Control Objective',
  process_walkthrough: 'Process activity and walkthrough details',
  control_relies_on_ipe: 'Does the control rely on information produced by the entity?',
  audit_evidence_accuracy: 'Will we obtain audit evidence of the accuracy and completeness of information produced by the entity by testing controls or by performing procedures directly on the information?',
  ipe_reference: 'IPE Reference',
  key_control: 'Key Control (Yes / No)',
  application_name: 'Application Name',
  control_performer: 'Control Performer',
  control_owner: 'Process Owner',
  control_type_fo: 'Type of control (Operational/Financial)',
  control_type_ma: 'Type of control (Manual/ Automated)',
  nature_of_control: 'Nature of Control (Preventive or Detective)',
  control_frequency: 'Frequency of Control',
  whether_fraud_risks_exist: 'Whether fraud risk exists?',
  completeness: 'Completeness',
  existence_occurrence: 'Existence & Occurrence',
  rights_and_obligation: 'Rights and Obligations',
  valuation_and_allocation: 'Valuation & Allocation',
  presentation_and_disclosure: 'Presentation and Disclosure'
  }

  // Exact display order requested for Control section (frontend-only ordering/wording)
  const controlSectionFieldOrder = [
    'control_objective',
    'standard_control_description',
    'process_walkthrough',
    'control_type_fo',
    'control_relies_on_ipe',
    'ipe_reference',
    'audit_evidence_accuracy',
    'nature_of_control',
    'control_type_ma',
    'key_control',
    'application_name',
    'control_frequency',
    'control_performer',
    'control_owner',
    'whether_fraud_risks_exist',
  ]

  const renderAssignableUserAutocomplete = (fieldId, labelText) => {
    const selectedEmail = (formData[fieldId] || '').trim()
    const optionsForField = mergeAssignableUserIntoOptions(ownerOptions, selectedEmail)
    const selectedUser = selectedEmail
      ? optionsForField.find(
          (u) => (u.email_id || '').trim().toLowerCase() === selectedEmail.toLowerCase()
        ) ?? { email_id: selectedEmail, emp_name: '' }
      : null

    return (
      <Autocomplete
        key={fieldId}
        id={fieldId}
        options={optionsForField}
        loading={usersLoading}
        value={selectedUser}
        onChange={(_, newValue) => {
          setFormData((prev) => ({
            ...prev,
            [fieldId]: newValue?.email_id?.trim() || '',
          }))
        }}
        onInputChange={(_, newInputValue, reason) => {
          if (reason === 'reset') return
          if (reason === 'clear') {
            fetchAssignableUsers({
              q: '',
              limit: ASSIGNABLE_USER_INITIAL_LIMIT,
            })
            return
          }
          if (assignableUserSearchDebounceRef.current) {
            clearTimeout(assignableUserSearchDebounceRef.current)
          }
          assignableUserSearchDebounceRef.current = setTimeout(() => {
            const q = newInputValue.trim()
            fetchAssignableUsers({
              q,
              limit: q ? ASSIGNABLE_USER_SEARCH_LIMIT : ASSIGNABLE_USER_INITIAL_LIMIT,
            })
          }, 300)
        }}
        onOpen={() => {
          if (ownerOptions.length === 0) {
            fetchAssignableUsers({
              q: '',
              limit: ASSIGNABLE_USER_INITIAL_LIMIT,
            })
          }
        }}
        getOptionLabel={(option) => option?.emp_name?.trim() || option?.email_id || ''}
        isOptionEqualToValue={(option, value) =>
          (option?.email_id || '').trim().toLowerCase() ===
          (value?.email_id || '').trim().toLowerCase()
        }
        filterOptions={(options) => options}
        freeSolo={false}
        clearOnEscape
        disableClearable={false}
        renderOption={(props, option) => (
          <Box component="li" {...props}>
            <Box sx={{ display: 'flex', flexDirection: 'column' }}>
              <Typography variant="body2">{option.emp_name || '-'}</Typography>
              <Typography variant="caption" color="text.secondary">
                {option.email_id || '-'}
              </Typography>
            </Box>
          </Box>
        )}
        renderInput={(params) => (
          <TextField
            {...params}
            label={labelText}
            placeholder="Search by name or email…"
            variant="outlined"
            disabled={loading}
          />
        )}
        disabled={loading}
      />
    )
  }

  return (
    <Box 
      sx={{ 
        width: '100%',
        maxWidth: FORM_DETAIL_MAX_WIDTH,
        mx: 'auto',
        px: 0, 
        py: 0,
      }}
    >
      <Box sx={{ width: '100%' }}>
        <Paper 
          elevation={3}
          sx={{
            p: 4,
            backgroundColor: theme.palette.background.paper,
            borderRadius: 2,
          }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
            <IconButton
              onClick={() => navigate('/company_co/racm-management')}
              sx={{
                mr: 2,
                color: theme.palette.text.primary,
                '&:hover': {
                  backgroundColor: theme.palette.mode === 'dark' 
                    ? 'rgba(255, 255, 255, 0.08)' 
                    : 'rgba(0, 0, 0, 0.04)',
                },
              }}
              aria-label="back to dashboard"
            >
              <ArrowBackIcon />
            </IconButton>
            <Typography
              variant="h4"
              component="h1"
              sx={{
                fontWeight: 700,
                color: 'text.primary',
                flex: 1,
                letterSpacing: '-0.02em',
                position: 'relative',
                pl: { xs: 0, sm: 1.75 },
              }}
            >
              Create RACM
            </Typography>
          </Box>

          <form onSubmit={handleSubmit}>
            {/* Top section: Business Process, Financial Year & Unit */}
            <Box
              sx={{
                mb: 4,
                display: 'grid',
                gridTemplateColumns: {
                  xs: '1fr',
                  md: 'repeat(3, 1fr)',
                },
                gap: 3,
              }}
            >
              {['business_process', 'financial_year', 'unit_id'].map((field) => {
                const label = fieldLabels[field]
                const value = formData[field] || ''
                const options =
                  field === 'business_process'
                    ? businessProcessOptions
                    : field === 'financial_year'
                      ? financialYearOptions
                      : unitOptions

                return (
                  <FormControl
                    key={field}
                    fullWidth
                    required
                  >
                    <InputLabel id={`${field}-label`}>{label}</InputLabel>
                    <Select
                      labelId={`${field}-label`}
                      id={field}
                      name={field}
                      value={value}
                      label={label}
                      onChange={async (e) => {
                        handleChange(e)
                        if (field !== 'business_process') return
                        const selectedProcess = String(e.target.value || '').trim()
                        if (!selectedProcess || !companyIdentifier) return
                        try {
                          const preview = await checkControlNumberPreview({
                            businessProcess: selectedProcess,
                            controlNumber: '',
                          })
                          if (!preview.generated) return
                          setFormData((prev) => {
                            const currentCn = String(prev.control_number || '').trim()
                            if (!currentCn || controlNumberMeta.autoGenerated) {
                              return { ...prev, control_number: preview.generated }
                            }
                            return prev
                          })
                          setControlNumberMeta((prev) => ({
                            ...prev,
                            autoGenerated: true,
                            duplicate: false,
                            available: false,
                          }))
                        } catch (error) {
                          console.error('Control number auto-generation error:', error)
                        }
                      }}
                      variant="outlined"
                      disabled={
                        loading ||
                        (field === 'unit_id' && unitOptions.length === 0) ||
                        (field === 'business_process' && businessProcessesLoading)
                      }
                    >
                      {options.map((option) => (
                        <MenuItem
                          key={field === 'unit_id' ? option.unit_id || option.id : option}
                          value={field === 'unit_id' ? option.unit_id : option}
                        >
                          {field === 'unit_id' ? option.unit_name || option.unit_id : option}
                        </MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                )
              })}
            </Box>

            {/* Process and risk section */}
            <Box
              sx={{
                mb: 4,
                borderTop: '2px solid',
                borderColor: 'divider',
                pt: 3,
              }}
            >
              <Typography
                variant="h6"
                component="h2"
                sx={{
                  fontWeight: 700,
                  mb: 3,
                  color: 'text.primary',
                  fontSize: '1.125rem',
                }}
              >
                Process and risk
              </Typography>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: {
                    xs: '1fr',
                    md: 'repeat(2, 1fr)',
                  },
                  gap: 3,
                }}
              >
                {['control_number', 'area', 'sub_process', 'risk_heat', 'risk_description'].map((field) => {
                  const label = fieldLabels[field]
                  const value = formData[field] || ''
                  const isMultiline = multilineFields.includes(field)
                  const isConfiguredDropdown = Object.prototype.hasOwnProperty.call(dropdownOptions, field)

                  if (isConfiguredDropdown) {
                    const options = dropdownOptions[field]
                    const selectedValue = dropdownSelections[field] || (options.includes(value) ? value : '')
                    const isOtherSelected = selectedValue === 'Other'

                    return (
                      <Box key={field}>
                        <FormControl fullWidth disabled={loading}>
                          <InputLabel id={`${field}-label`}>{label}</InputLabel>
                          <Select
                            labelId={`${field}-label`}
                            id={field}
                            name={field}
                            value={selectedValue}
                            label={label}
                            onChange={(e) => handleDropdownChange(field, e.target.value)}
                            variant="outlined"
                          >
                            {options.map((option) => (
                              <MenuItem key={option} value={option}>
                                {option}
                              </MenuItem>
                            ))}
                          </Select>
                        </FormControl>
                        {isOtherSelected && (
                          <TextField
                            sx={{ mt: 1.5 }}
                            fullWidth
                            label={`${label} (Other)`}
                            value={otherValues[field] || value || ''}
                            onChange={(e) => handleOtherValueChange(field, e.target.value)}
                            disabled={loading}
                          />
                        )}
                      </Box>
                    )
                  }

                  return (
                    <TextField
                      key={field}
                      name={field}
                      label={label}
                      value={value}
                      onChange={handleChange}
                      fullWidth
                      multiline={isMultiline}
                      rows={isMultiline ? 4 : 1}
                      variant="outlined"
                      disabled={loading}
                      sx={{
                        gridColumn: isMultiline
                          ? {
                              xs: '1',
                              md: '1 / -1',
                            }
                          : undefined,
                      }}
                    />
                  )
                })}
              </Box>
            </Box>

            {/* Assertions section */}
            <Box
              sx={{
                mb: 4,
                borderTop: '2px solid',
                borderColor: 'divider',
                pt: 3,
              }}
            >
              <Typography
                variant="h6"
                component="h2"
                sx={{
                  fontWeight: 700,
                  mb: 3,
                  color: 'text.primary',
                  fontSize: '1.125rem',
                }}
              >
                Assertions
              </Typography>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: {
                    xs: '1fr',
                    md: 'repeat(2, 1fr)',
                  },
                  gap: 3,
                }}
              >
                {['completeness', 'existence_occurrence', 'valuation_and_allocation', 'rights_and_obligation', 'presentation_and_disclosure'].map((field) => {
                  const label = fieldLabels[field]
                  const checked = !!formData[field]

                  return (
                    <Box
                      key={field}
                      sx={{
                        border: '1px solid',
                        borderColor: 'divider',
                        borderRadius: 1.5,
                        px: 2,
                        py: 1.5,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        gap: 2,
                      }}
                    >
                      <Typography sx={{ fontWeight: 600, color: 'text.primary' }}>{label}</Typography>
                      <Checkbox
                        checked={checked}
                        onChange={handleAssertionToggle(field)}
                        disabled={loading}
                        inputProps={{ 'aria-label': label }}
                      />
                    </Box>
                  )
                })}
              </Box>
            </Box>

            {/* Remaining fields section – Control */}
            <Box
              sx={{
                borderTop: '2px solid',
                borderColor: 'divider',
                pt: 3,
                mb: 3,
              }}
            >
              <Typography
                variant="h6"
                component="h2"
                sx={{
                  fontWeight: 700,
                  mb: 3,
                  color: 'text.primary',
                  fontSize: '1.125rem',
                }}
              >
                Control
              </Typography>
              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: {
                    xs: '1fr',
                    md: 'repeat(2, 1fr)',
                  },
                  gap: 3,
                }}
              >
                {controlSectionFieldOrder
                  .map((field) => {
                    const label = fieldLabels[field] || field.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase())
                    const value = formData[field] || ''
                    const isMultiline = multilineFields.includes(field)
                    const isConfiguredDropdown = Object.prototype.hasOwnProperty.call(dropdownOptions, field)

                    if (field === 'control_performer' || field === 'control_owner') {
                      return renderAssignableUserAutocomplete(field, label)
                    }

                    if (isConfiguredDropdown) {
                      const options = dropdownOptions[field]
                      const selectedValue = dropdownSelections[field] || (options.includes(value) ? value : '')
                      const isOtherSelected = selectedValue === 'Other'

                      return (
                        <Box key={field}>
                          <FormControl fullWidth disabled={loading}>
                            <InputLabel id={`${field}-label`}>{label}</InputLabel>
                            <Select
                              labelId={`${field}-label`}
                              id={field}
                              name={field}
                              value={selectedValue}
                              label={label}
                              onChange={(e) => handleDropdownChange(field, e.target.value)}
                              variant="outlined"
                            >
                              {options.map((option) => (
                                <MenuItem key={option} value={option}>
                                  {option}
                                </MenuItem>
                              ))}
                            </Select>
                          </FormControl>
                          {isOtherSelected && (
                            <TextField
                              sx={{ mt: 1.5 }}
                              fullWidth
                              label={`${label} (Other)`}
                              value={otherValues[field] || value || ''}
                              onChange={(e) => handleOtherValueChange(field, e.target.value)}
                              disabled={loading}
                            />
                          )}
                        </Box>
                      )
                    }

                    return (
                      <TextField
                        key={field}
                        name={field}
                        label={field === 'control_number' && controlNumberMeta.autoGenerated
                          ? `${label} (auto-generated)`
                          : label}
                        value={value}
                        onChange={handleChange}
                        fullWidth
                        multiline={isMultiline}
                        rows={isMultiline ? 4 : 1}
                        variant="outlined"
                        disabled={loading}
                        error={field === 'control_number' && controlNumberMeta.duplicate}
                        helperText={field === 'control_number' && controlNumberMeta.duplicate
                          ? 'Control Number already exists'
                          : (field === 'control_number' && controlNumberMeta.available
                            ? 'Control Number is available'
                            : undefined)}
                        FormHelperTextProps={{
                          sx: field === 'control_number' && controlNumberMeta.available
                            ? { color: 'success.main' }
                            : undefined,
                        }}
                        InputProps={{
                          endAdornment: field === 'control_number' ? (
                            <InputAdornment position="end" sx={{ gap: 1 }}>
                              {controlNumberMeta.checkingDuplicate ? 'Checking...' : null}
                              <Button
                                size="small"
                                variant="text"
                                disabled={loading || businessProcessesLoading || controlNumberMeta.checkingDuplicate}
                                onMouseDown={(event) => event.preventDefault()}
                                onClick={handleGenerateControlNumber}
                                sx={{ minWidth: 'auto', px: 1, textTransform: 'none', fontWeight: 700 }}
                              >
                                Generate
                              </Button>
                            </InputAdornment>
                          ) : undefined,
                        }}
                        sx={{
                          gridColumn: isMultiline
                            ? {
                                xs: '1',
                                md: '1 / -1',
                              }
                            : undefined,
                        }}
                      />
                    )
                  })}
              </Box>
            </Box>

            {/* Submit Button */}
            <Box sx={{ display: 'flex', gap: 2, mt: 4, flexWrap: 'wrap' }}>
              <Button
                type="submit"
                disabled={
                  loading ||
                  businessProcessesLoading ||
                  !formData.business_process ||
                  !formData.financial_year ||
                  !formData.unit_id
                }
                variant="contained"
                color="secondary"
                sx={{
                  py: 1.5,
                  px: 3,
                  minWidth: 180,
                  fontSize: theme.typography.customSizes.medium,
                  fontWeight: 600,
                  textTransform: 'none',
                }}
              >
                {loading ? 'Creating...' : 'Create RACM'}
              </Button>
            </Box>
          </form>
        </Paper>
      </Box>
    </Box>
  )
}

export default CreateControlForm
